### ISSUE TITLE
Upgrade aws-sdk-dynamodb to 0.12.0

### ISSUE THREAD

**Issue by CumpsD** [serverlesstechnology/dynamo-es#1]
https://github.com/serverlesstechnology/dynamo-es/blob/master/Cargo.toml#L17

```
  --> hello2\src\main.rs:30:9
   |
30 |         client,
   |         ^^^^^^ expected struct `aws_sdk_dynamodb::client::Client`, found struct `aws_sdk_dynamodb::Client`
   |
   = note: perhaps two different versions of crate `aws_sdk_dynamodb` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hello2` due to previous error
```

**Comment by serverlesstechnology** [comment]
Thanks @CumpsD, I'll try to get this out shortly.

**Comment by serverlesstechnology** [comment]
Published update in v0.4.1

**Comment by CumpsD** [comment]
Thanks!

**Comment by CumpsD** [comment]
Here I am again ;) Can you bump it to 0.17.0 please?

**Comment by serverlesstechnology** [comment]
Thanks @CumpsD , making this change along with the version bump to get everything clippy happy with Rust 1.63

Note: please feel free to re-open this ticket in the future, that makes it a little easier to find (though I'm expecting that we'll have a v1.0 after Re:Invent in a few months).

**Comment by CumpsD** [comment]
Can't re-open it for some reason, I'll create a new one in the future :)
