### ISSUE TITLE
Service error when returning an empty events vec

### ISSUE THREAD

**Issue by oco-adam** [serverlesstechnology/dynamo-es#8]
Hi,

First of all, thanks for the excellent framework - it looks great and we're just trying to use it in one of our (internal) production services.

However, I'm getting a `service error` when I'm trying to return no events in an aggregate handler. In particular I have a handler like this:

```
    async fn handle(
        &self,
        command: Self::Command,
        _services: &Self::Services,
    ) -> Result<Vec<Self::Event>, Self::Error> {
        match command {
            S3ImageCommand::ArchiveImageDetails {} => match self {
...
            },
            S3ImageCommand::SaveImageDetails { details } => match self {
                S3Image::Initial => Ok(vec![S3ImageEvent::ImageDetailsCreated { details }]),
                S3Image::Present {
                    details: existing_details,
                } => {
                    if details == existing_details.clone() {
                        Ok(vec![]) // Idempotency
                    } else {
                        Ok(vec![S3ImageEvent::ImageDetailsUpdated { details }])
                    }
                }
...
```

and when the line
` Ok(vec![]) // Idempotency`
is called, I'm getting a Service error in production.

However, if `  Ok(vec![S3ImageEvent::ImageDetailsUpdated { details }])` is returned, the event is inserted fine.

I tried quickly to make a failing test for you in a fork, but I couldn't get your tests to run locally - I'm getting errors of the form `message: Some("The Access Key ID or security token is invalid."), ` when I fork this repo and run the tests locally.

Any help with this would be much appreciated, or if you could give me some guidance on how to get the tests working then I can potentially try and help out with this, if it's a genuine bug and not something I've overlooked on my end.

**Comment by davegarred** [comment]
Hi @oco-adam, thanks for the feedback. The AWS Rust SDK is still in Developer Preview and, up to now at least, has changed often, so any extra eyes on this package is appreciated.

The local issue appears to be added security in the latest docker image. I've [pushed a change](https://github.com/serverlesstechnology/dynamo-es/commit/9d9b7a25238196f87619324fd18fa2f925e754ce) to fix this which should work for you.

I have not recreated the remote error yet but I'm investigating.

**Comment by oco-adam** [comment]
Hi @davegarred thanks for the quick response!

I've got the local tests working now, after your fix, so I'll try and make a failing test, or minimal reproduction and let you know

**Comment by oco-adam** [comment]
Hi @davegarred, I made a pull request #9  that handles the case of an empty events vec, at the level of the events repo. This fixes my service error issue in production.

I also added a few lines to your main test case, demonstrating how trying to commit an empty events vec results in an error.

**Comment by davegarred** [comment]
Looks good, I've added one request.
